export const MNEMONIC = "abandon ability able about above absent absorb abstract absurd abuse access accident"
export const UserName = "xm"
export const PASSWd = "1231231231231"
export const NEXUS_WEB_URL = "https://nexus-e2e.vercel.app/"
export const NEXUS_WEB_LOCAL_URL = "http://localhost:3000/"
export const fullOwnership = "fullOwnership"
export const ruleBasedOwnership = "ruleBasedOwnership"
